[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "mlb-led-scoreboard-boards"
version = "9.0.0"
description = "Clock and countdown screens for the MLB LED Scoreboard"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points.'bullpen.mlbled.plugin']
"clock" = "mlb_led_scoreboard_boards.clock:load"
"countdown" = "mlb_led_scoreboard_boards.countdown:load"
